### ISSUE TITLE
Same page topic upvote

### ISSUE THREAD

**Issue by ogourment** [MeteorMTL/magnet#10]
Right now, when you upvote a topic, it goes to the Topic edit page; you have to click the browser back button to be able to vote again.

**Comment by pcuci** [comment]
@ogourment the idea was to vote indirectly through your actions. Revisiting the page later (through the natural flow of exploring keywords) up-votes automatically; now we know you really care about this keyword as you visit it again and again.

@David-Ro what do you think about up-voting on the topic page? Extra thumb-up button

**Comment by David-Ro** [comment]
yes, an extra upvote while viewing on the team page, OK.

**Comment by David-Ro** [comment]
Must now associate keywords per team, independent of keywords per person. These could be default-populated as the overlap, exclusive-or, common to all team joiners. Still need to have top two team admin people who can add-remove team keywords.

**Comment by pcuci** [comment]
@ogourment now when you view a keyword it up-votes automatically up until 20 points, then you must down-vote (essentially curate) your own keywords to signal intentions to the community. Opened #43 for team keywords

**Comment by ogourment** [comment]
I've seen many people, including myself, confused by the automatic vote. I would suggest a bubble message saying that you have voted for the keyword when the keyword page is displayed.

**Comment by pcuci** [comment]
I also like Discourse's up-vote on link click, maybe we can build on that, e.g.: https://forums.meteor.com/t/what-about-meteor-on-uservoice/7813 - when you click, it waits a second, ups the count (so you can see it), then it takes you to the new page. It also doesn't double-count, which is an interesting design choice - only one upvote per user.

**Comment by pcuci** [comment]
Opened related issue #44 Re-engineer key-words
