### ISSUE TITLE
instead of 'My Profile' tab, it would be clearer for user to say their name or their email 

### ISSUE THREAD

**Issue by TedEwanchyna** [MeteorMTL/magnet#19]
another simple fix: the id is first_name but the event is looking for name...

**Comment by pcuci** [comment]
@TedEwanchyna - how would the log-out link work?

We're not using the standard accounts-ui, rather we use OrionJS' dependency https://github.com/meteor-useraccounts/core/

**Comment by TedEwanchyna** [comment]
not sure about log out just in navigation:
 in navigation.html replace 'My Profile with {{myName}}'s Profile
and in navigation.js add:
Template.Navigation.helpers({
  myName: function (){ 
    // if a user exists use the profile name, if that is no good use the email if all fails use 'who'
    return Meteor.user() ? 
             Meteor.user().profile.name ? 
               Meteor.user().profile.name : 
                 Meteor.user().emails[0].address ?
                   Meteor.user().emails[0].address : "who"
           : "who";
  }
});

**Comment by TedEwanchyna** [comment]
... i may have inadvertently created an extra issue #20 (ooops)

**Comment by pcuci** [comment]
@TedEwanchyna wanna give that a try? I think it'll work fine, the `Sign Out` button will be right next to the Name (Profile) tab

**Comment by pcuci** [comment]
Implemented by @TedEwanchyna
