### ISSUE TITLE
Let team originator person move into passive role + hand baton over to...

### ISSUE THREAD

**Issue by pcuci** [MeteorMTL/magnet#41]
I see a colored band around the avatar of the team creator (originator). Great. 

Can we make it possible for this person to hand the key role over to anohter team member? Then, there could be two colors. The second person gets an orange color for example.558bad32a64d3a7c52078fba

**Comment by TedEwanchyna** [comment]
The team creator is still being used as if it were the team leader role. We will introduce the proper use of roles shortly.

The "creator" can be handed over to another team member. Also the team creator can add new players. When the creator leaves the team his role is assigned to 'another' team member.

**Comment by pcuci** [comment]
Fixed by @TedEwanchyna
