### ISSUE TITLE
Team keywords

### ISSUE THREAD

**Issue by pcuci** [MeteorMTL/magnet#43]
Must now associate keywords per team, independent of keywords per person. These could be default-populated as the overlap, exclusive-or, common to all team joiners. Still need to have top two team admin people who can add-remove team keywords.

**Comment by pcuci** [comment]
Select from shared keywords, the ones that relate to the team

Ability to add new keyword to team only (not necessarily to self)

**Comment by TedEwanchyna** [comment]
ok i have a rudimentary version working

**Comment by pcuci** [comment]
@TedEwanchyna - cool, feel free to merge your own pull request
