### ISSUE TITLE
Link to My Profile

### ISSUE THREAD

**Issue by ogourment** [MeteorMTL/magnet#9]
Right now the only way to access your profile is to sign out and back in.

**Comment by TedEwanchyna** [comment]
I am trying to understand this problem. I have logged in and can access my profile on the front page.
What exactly do have to do to 'recreate this issue where I must "sign out and log back in" again?

**Comment by ogourment** [comment]
Click on Teaming, for example, then try to take a profile photo, or change any other info about you. You'll find that there's no link to access your profile page. Unless I missed it and it would be a usability issue 😄

**Comment by TedEwanchyna** [comment]
It may be a usability issue. I think the same problem exists whether or not you change to a new tab. There is no feedback to the user when a text field is changed - it just changes, which, in itself is not bad but what is confusing is also having the 'Save Profile' button. I have to explore more. I am having trouble taking my photo.

**Comment by ogourment** [comment]
@pcuci (sorry, was wrong @paulcu )
What's your take on this?  Just add a link to My Profile in the main menu?

**Comment by TedEwanchyna** [comment]
I think there is a problem beyond this and the sign out/sign in again is a red herring. I can not take a picture with the new code. I can with an earlier version of the code. Something broke.

As for aesthetics, I think the profile would be better accessed as @ogourment suggests rather then being the bottom part of another page...

**Comment by ogourment** [comment]
Oh, I see; so it is a usability issue. The Profile is accessible from the bottom of the Keywords page (which you can get to from either the Keywords menu item, or by clicking on SpeedTeam).

**Comment by TedEwanchyna** [comment]
yes I don't think it is in the right place. Also I think I found the problem with the camera it is broken but the fix is easy. The button event has to be changes, then it will work
 Template.Me.events({
change:
     'click button':
to: 
     'click .material-icons':
